FROM teraokaseiko/digi-node:1.0

# 一行で書きたいんだが・・・。これは期待通りに動作しない。
# COPY ../[abnprsv]* /app/
# 仕方がないのでひとつずつコピーするか・・・。

COPY ./app.js /app/app.js
COPY ./bin /app/bin
COPY ./node_modules /app/node_modules
COPY ./package.json /app/package.json
COPY ./public /app/public
COPY ./routes /app/routes
COPY ./test /app/test
COPY ./views /app/views
